In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import plotly.express as px
import math
from sklearn.feature_extraction import DictVectorizer
from sklearn.neural_network import MLPRegressor
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score ,confusion_matrix



# Loading of train data set

In [ ]:
train=pd.read_csv("train.csv")
train

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [ ]:
train.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [ ]:
print(train['MSSubClass'].nunique())
train['MSSubClass'].value_counts()


15


20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: MSSubClass, dtype: int64

In [ ]:
print(train['MSZoning'].nunique())
print(train['MSZoning'].value_counts())

5
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64


In [ ]:
print(train['FireplaceQu'].nunique())
print(train['FireplaceQu'].value_counts())

5
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: FireplaceQu, dtype: int64


In [ ]:
train.drop("Alley",axis=1, inplace=True)
train.drop("PoolQC",axis=1, inplace=True)
train.drop("Fence",axis=1, inplace=True)
train.drop("MiscFeature",axis=1, inplace=True)
train.drop("FireplaceQu",axis=1, inplace=True)
train

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
0        1          60       RL         65.0     8450   Pave      Reg   
1        2          20       RL         80.0     9600   Pave      Reg   
2        3          60       RL         68.0    11250   Pave      IR1   
3        4          70       RL         60.0     9550   Pave      IR1   
4        5          60       RL         84.0    14260   Pave      IR1   
...    ...         ...      ...          ...      ...    ...      ...   
1455  1456          60       RL         62.0     7917   Pave      Reg   
1456  1457          20       RL         85.0    13175   Pave      Reg   
1457  1458          70       RL         66.0     9042   Pave      Reg   
1458  1459          20       RL         68.0     9717   Pave      Reg   
1459  1460          20       RL         75.0     9937   Pave      Reg   

     LandContour Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0            Lvl    AllPub    Inside  ...             0         0           0   
1            Lvl    AllPub       FR2  ...             0         0           0   
2            Lvl    AllPub    Inside  ...             0         0           0   
3            Lvl    AllPub    Corner  ...           272         0           0   
4            Lvl    AllPub       FR2  ...             0         0           0   
...          ...       ...       ...  ...           ...       ...         ...   
1455         Lvl    AllPub    Inside  ...             0         0           0   
1456         Lvl    AllPub    Inside  ...             0         0           0   
1457         Lvl    AllPub    Inside  ...             0         0           0   
1458         Lvl    AllPub    Inside  ...           112         0           0   
1459         Lvl    AllPub    Inside  ...             0         0           0   

     PoolArea MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0           0       0      2    2008        WD         Normal     208500  
1           0       0      5    2007        WD         Normal     181500  
2           0       0      9    2008        WD         Normal     223500  
3           0       0      2    2006        WD        Abnorml     140000  
4           0       0     12    2008        WD         Normal     250000  
...       ...     ...    ...     ...       ...            ...        ...  
1455        0       0      8    2007        WD         Normal     175000  
1456        0       0      2    2010        WD         Normal     210000  
1457        0    2500      5    2010        WD         Normal     266500  
1458        0       0      4    2010        WD         Normal     142125  
1459        0       0      6    2008        WD         Normal     147500  

[1460 rows x 76 columns]

In [ ]:
print(train['MSSubClass'].nunique())
print(train['MSSubClass'].value_counts())


15
20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: MSSubClass, dtype: int64


In [ ]:
print(train['MSZoning'].nunique())
print(train['MSZoning'].value_counts())


5
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64


In [ ]:
print(train['LotShape'].nunique())
print(train['LotShape'].value_counts())

4
Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64


In [ ]:
print(train['LandContour'].nunique())
print(train['LandContour'].value_counts())

4
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64


In [ ]:
print(train['Utilities'].nunique())
print(train['Utilities'].value_counts())


2
AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64


In [ ]:
print(train['LotConfig'].nunique())
print(train['LotConfig'].value_counts())

5
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64


In [ ]:
print(train['PoolArea'].nunique())
print(train['PoolArea'].value_counts())

8
0      1453
512       1
648       1
576       1
555       1
480       1
519       1
738       1
Name: PoolArea, dtype: int64


In [ ]:
train

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
0        1          60       RL         65.0     8450   Pave      Reg   
1        2          20       RL         80.0     9600   Pave      Reg   
2        3          60       RL         68.0    11250   Pave      IR1   
3        4          70       RL         60.0     9550   Pave      IR1   
4        5          60       RL         84.0    14260   Pave      IR1   
...    ...         ...      ...          ...      ...    ...      ...   
1455  1456          60       RL         62.0     7917   Pave      Reg   
1456  1457          20       RL         85.0    13175   Pave      Reg   
1457  1458          70       RL         66.0     9042   Pave      Reg   
1458  1459          20       RL         68.0     9717   Pave      Reg   
1459  1460          20       RL         75.0     9937   Pave      Reg   

     LandContour Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0            Lvl    AllPub    Inside  ...             0         0           0   
1            Lvl    AllPub       FR2  ...             0         0           0   
2            Lvl    AllPub    Inside  ...             0         0           0   
3            Lvl    AllPub    Corner  ...           272         0           0   
4            Lvl    AllPub       FR2  ...             0         0           0   
...          ...       ...       ...  ...           ...       ...         ...   
1455         Lvl    AllPub    Inside  ...             0         0           0   
1456         Lvl    AllPub    Inside  ...             0         0           0   
1457         Lvl    AllPub    Inside  ...             0         0           0   
1458         Lvl    AllPub    Inside  ...           112         0           0   
1459         Lvl    AllPub    Inside  ...             0         0           0   

     PoolArea MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0           0       0      2    2008        WD         Normal     208500  
1           0       0      5    2007        WD         Normal     181500  
2           0       0      9    2008        WD         Normal     223500  
3           0       0      2    2006        WD        Abnorml     140000  
4           0       0     12    2008        WD         Normal     250000  
...       ...     ...    ...     ...       ...            ...        ...  
1455        0       0      8    2007        WD         Normal     175000  
1456        0       0      2    2010        WD         Normal     210000  
1457        0    2500      5    2010        WD         Normal     266500  
1458        0       0      4    2010        WD         Normal     142125  
1459        0       0      6    2008        WD         Normal     147500  

[1460 rows x 76 columns]

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [ ]:
LotShape=pd.get_dummies(train['LotShape'], drop_first=True) 
RoofStyle=pd.get_dummies(train['RoofStyle'], drop_first=True)
HouseStyle =pd.get_dummies(train['HouseStyle'], drop_first=True)
BldgType =pd.get_dummies(train['BldgType'], drop_first=True)
Condition2 =pd.get_dummies(train['Condition2'], drop_first=True)

Condition1=pd.get_dummies(train['Condition1'], drop_first=True)
Neighborhood =pd.get_dummies(train['Neighborhood'], drop_first=True)
Utilities=pd.get_dummies(train['Utilities'], drop_first=True)
LandContour=pd.get_dummies(train['LandContour'], drop_first=True) 
Street=pd.get_dummies(train['Street'], drop_first=True)
ExterCond=pd.get_dummies(train['ExterCond'], drop_first=True)
ExterQual=pd.get_dummies(train['ExterQual'], drop_first=True)
MasVnrType=pd.get_dummies(train['MasVnrType'], drop_first=True)
Exterior2nd=pd.get_dummies(train['Exterior2nd'], drop_first=True)
Exterior1st=pd.get_dummies(train['Exterior1st'], drop_first=True)
MSZoning=pd.get_dummies(train['MSZoning'], drop_first=True)
BsmtFinType2=pd.get_dummies(train['BsmtFinType2'], drop_first=True)
BsmtFinType1=pd.get_dummies(train['BsmtFinType1'], drop_first=True)
BsmtExposure=pd.get_dummies(train['BsmtExposure'], drop_first=True)
BsmtCond=pd.get_dummies(train['BsmtCond'], drop_first=True)

BsmtQual=pd.get_dummies(train['BsmtQual'], drop_first=True)
Foundation=pd.get_dummies(train['Foundation'], drop_first=True)

Functional=pd.get_dummies(train['Functional'], drop_first=True)
Electrical=pd.get_dummies(train['Electrical'], drop_first=True)

CentralAir=pd.get_dummies(train['CentralAir'], drop_first=True)
KitchenQual=pd.get_dummies(train['KitchenQual'], drop_first=True)
HeatingQC=pd.get_dummies(train['HeatingQC'], drop_first=True)
Heating=pd.get_dummies(train['Heating'], drop_first=True)

LotConfig=pd.get_dummies(train['LotConfig'], drop_first=True)
LandSlope=pd.get_dummies(train['LandSlope'], drop_first=True)
SaleCondition=pd.get_dummies(train['SaleCondition'], drop_first=True)
SaleType=pd.get_dummies(train['SaleType'], drop_first=True)
PavedDrive=pd.get_dummies(train['PavedDrive'], drop_first=True)
GarageCond=pd.get_dummies(train['GarageCond'], drop_first=True)
GarageQual=pd.get_dummies(train['GarageQual'], drop_first=True)
GarageFinish=pd.get_dummies(train['GarageFinish'], drop_first=True)
GarageType=pd.get_dummies(train['GarageType'], drop_first=True)



In [ ]:
train=pd.concat([train,MSZoning,Street,LotShape,LandContour,RoofStyle ,BldgType ,Condition1,Neighborhood,ExterCond,ExterQual,MasVnrType
,BsmtFinType2,BsmtFinType1,BsmtExposure,BsmtCond,BsmtQual,Foundation,Functional,CentralAir, KitchenQual,HeatingQC,GarageCond,GarageFinish, 
GarageType,LotConfig,LandSlope, SaleCondition, SaleType,PavedDrive],axis=1)

train.drop([ 'MSZoning','Street','LotShape','LandContour','Utilities','RoofMatl','RoofStyle','HouseStyle' ,'BldgType','Condition2' ,'Condition1','Neighborhood',
'ExterCond','ExterQual','MasVnrType','Exterior2nd','Exterior1st', 'BsmtFinType2','BsmtFinType1','BsmtExposure','BsmtCond','BsmtQual','Foundation',
'Functional','Electrical','CentralAir','KitchenQual','HeatingQC','Heating','GarageCond','GarageQual','GarageFinish', 'GarageType','LotConfig',
'LandSlope', 'SaleCondition', 'SaleType','PavedDrive'],axis=1, inplace=True)

#train

In [ ]:
x=train.drop("SalePrice",axis=1)
y=train['SalePrice']

# Removing missing value from train set

In [ ]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan, strategy='median', verbose=0)
imputer=imputer.fit(x)
x_imp=imputer.transform(x)
train_x=pd.DataFrame(x_imp)
train_x



0     1     2        3    4    5       6       7      8      9    \
0        1.0  60.0  65.0   8450.0  7.0  5.0  2003.0  2003.0  196.0  706.0   
1        2.0  20.0  80.0   9600.0  6.0  8.0  1976.0  1976.0    0.0  978.0   
2        3.0  60.0  68.0  11250.0  7.0  5.0  2001.0  2002.0  162.0  486.0   
3        4.0  70.0  60.0   9550.0  7.0  5.0  1915.0  1970.0    0.0  216.0   
4        5.0  60.0  84.0  14260.0  8.0  5.0  2000.0  2000.0  350.0  655.0   
...      ...   ...   ...      ...  ...  ...     ...     ...    ...    ...   
1455  1456.0  60.0  62.0   7917.0  6.0  5.0  1999.0  2000.0    0.0    0.0   
1456  1457.0  20.0  85.0  13175.0  6.0  6.0  1978.0  1988.0  119.0  790.0   
1457  1458.0  70.0  66.0   9042.0  7.0  9.0  1941.0  2006.0    0.0  275.0   
1458  1459.0  20.0  68.0   9717.0  5.0  6.0  1950.0  1996.0    0.0   49.0   
1459  1460.0  20.0  75.0   9937.0  5.0  6.0  1965.0  1965.0    0.0  830.0   

      ...  159  160  161  162  163  164  165  166  167  168  
0     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
2     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
3     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
4     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
1455  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1456  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1457  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1458  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1459  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  

[1460 rows x 169 columns]

In [ ]:
train_x=pd.DataFrame(x_imp)
train_x

0     1     2        3    4    5       6       7      8      9    \
0        1.0  60.0  65.0   8450.0  7.0  5.0  2003.0  2003.0  196.0  706.0   
1        2.0  20.0  80.0   9600.0  6.0  8.0  1976.0  1976.0    0.0  978.0   
2        3.0  60.0  68.0  11250.0  7.0  5.0  2001.0  2002.0  162.0  486.0   
3        4.0  70.0  60.0   9550.0  7.0  5.0  1915.0  1970.0    0.0  216.0   
4        5.0  60.0  84.0  14260.0  8.0  5.0  2000.0  2000.0  350.0  655.0   
...      ...   ...   ...      ...  ...  ...     ...     ...    ...    ...   
1455  1456.0  60.0  62.0   7917.0  6.0  5.0  1999.0  2000.0    0.0    0.0   
1456  1457.0  20.0  85.0  13175.0  6.0  6.0  1978.0  1988.0  119.0  790.0   
1457  1458.0  70.0  66.0   9042.0  7.0  9.0  1941.0  2006.0    0.0  275.0   
1458  1459.0  20.0  68.0   9717.0  5.0  6.0  1950.0  1996.0    0.0   49.0   
1459  1460.0  20.0  75.0   9937.0  5.0  6.0  1965.0  1965.0    0.0  830.0   

      ...  159  160  161  162  163  164  165  166  167  168  
0     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
2     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
3     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
4     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
1455  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1456  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1457  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1458  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1459  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  

[1460 rows x 169 columns]

In [ ]:
train.corr()['SalePrice'].sort_values(ascending=False)

SalePrice      1.000000
OverallQual    0.790982
GrLivArea      0.708624
GarageCars     0.640409
GarageArea     0.623431
                 ...   
None          -0.374468
Unf           -0.410608
TA            -0.452394
TA            -0.519298
TA            -0.589044
Name: SalePrice, Length: 170, dtype: float64

# loading test dataset

In [ ]:
test=pd.read_csv("test.csv")


In [ ]:
test.drop("Alley",axis=1, inplace=True)
test.drop("PoolQC",axis=1, inplace=True)
test.drop("Fence",axis=1, inplace=True)
test.drop("MiscFeature",axis=1, inplace=True)
test.drop("FireplaceQu",axis=1, inplace=True)

In [ ]:
LotShape=pd.get_dummies(test['LotShape'], drop_first=True)
RoofStyle=pd.get_dummies(test['RoofStyle'], drop_first=True)
BldgType =pd.get_dummies(test['BldgType'], drop_first=True)
Condition2 =pd.get_dummies(test['Condition2'], drop_first=True)
Condition1=pd.get_dummies(test['Condition1'], drop_first=True)
Neighborhood =pd.get_dummies(test['Neighborhood'], drop_first=True)
Utilities=pd.get_dummies(test['Utilities'], drop_first=True)
LandContour=pd.get_dummies(test['LandContour'], drop_first=True)  
Street=pd.get_dummies(test['Street'], drop_first=True)
ExterCond=pd.get_dummies(test['ExterCond'], drop_first=True)

ExterQual=pd.get_dummies(test['ExterQual'], drop_first=True)
MasVnrType=pd.get_dummies(test['MasVnrType'], drop_first=True)
Exterior2nd=pd.get_dummies(test['Exterior2nd'], drop_first=True)
Exterior1st=pd.get_dummies(test['Exterior1st'], drop_first=True)
MSZoning=pd.get_dummies(test['MSZoning'], drop_first=True) 

BsmtFinType2=pd.get_dummies(test['BsmtFinType2'], drop_first=True)
BsmtFinType1=pd.get_dummies(test['BsmtFinType1'], drop_first=True)
BsmtExposure=pd.get_dummies(test['BsmtExposure'], drop_first=True)
BsmtCond=pd.get_dummies(test['BsmtCond'], drop_first=True)
BsmtQual=pd.get_dummies(test['BsmtQual'], drop_first=True)
Foundation=pd.get_dummies(test['Foundation'], drop_first=True)

Functional=pd.get_dummies(test['Functional'], drop_first=True)
Electrical=pd.get_dummies(test['Electrical'], drop_first=True)
CentralAir=pd.get_dummies(test['CentralAir'], drop_first=True)
KitchenQual=pd.get_dummies(test['KitchenQual'], drop_first=True)
HeatingQC=pd.get_dummies(test['HeatingQC'], drop_first=True)
Heating=pd.get_dummies(test['Heating'], drop_first=True)

LotConfig=pd.get_dummies(test['LotConfig'], drop_first=True)
LandSlope=pd.get_dummies(test['LandSlope'], drop_first=True)
SaleCondition=pd.get_dummies(test['SaleCondition'], drop_first=True)
SaleType=pd.get_dummies(test['SaleType'], drop_first=True)
PavedDrive=pd.get_dummies(test['PavedDrive'], drop_first=True)

GarageCond=pd.get_dummies(test['GarageCond'], drop_first=True)
GarageQual=pd.get_dummies(test['GarageQual'], drop_first=True)
GarageFinish=pd.get_dummies(test['GarageFinish'], drop_first=True)
GarageType=pd.get_dummies(test['GarageType'], drop_first=True)



In [ ]:
test=pd.concat([test,MSZoning,Street,LotShape,LandContour,RoofStyle ,BldgType ,Condition1,Neighborhood,ExterCond,ExterQual,MasVnrType,
BsmtFinType2,BsmtFinType1,BsmtExposure,BsmtCond,BsmtQual,Foundation,Functional,CentralAir,KitchenQual,HeatingQC,GarageCond,GarageFinish, GarageType,
LotConfig,LandSlope, SaleCondition, SaleType,PavedDrive],axis=1)
test.drop([ 'MSZoning','Street','LotShape','LandContour','Utilities','RoofMatl','RoofStyle','HouseStyle' ,'BldgType','Condition2' ,'Condition1',
'Neighborhood','ExterCond','ExterQual','MasVnrType','Exterior2nd','Exterior1st', 'BsmtFinType2','BsmtFinType1','BsmtExposure','BsmtCond',
'BsmtQual','Foundation','Functional','Electrical','CentralAir','KitchenQual','HeatingQC','Heating','GarageCond','GarageQual',
'GarageFinish', 'GarageType','LotConfig','LandSlope', 'SaleCondition', 'SaleType','PavedDrive' ],axis=1, inplace=True)
test

Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
0     1461          20         80.0    11622            5            6   
1     1462          20         81.0    14267            6            6   
2     1463          60         74.0    13830            5            5   
3     1464          60         78.0     9978            6            6   
4     1465         120         43.0     5005            8            5   
...    ...         ...          ...      ...          ...          ...   
1454  2915         160         21.0     1936            4            7   
1455  2916         160         21.0     1894            4            5   
1456  2917          20        160.0    20000            5            7   
1457  2918          85         62.0    10441            5            5   
1458  2919          60         74.0     9627            7            5   

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  CWD  Con  ConLD  \
0          1961          1961         0.0       468.0  ...    0    0      0   
1          1958          1958       108.0       923.0  ...    0    0      0   
2          1997          1998         0.0       791.0  ...    0    0      0   
3          1998          1998        20.0       602.0  ...    0    0      0   
4          1992          1992         0.0       263.0  ...    0    0      0   
...         ...           ...         ...         ...  ...  ...  ...    ...   
1454       1970          1970         0.0         0.0  ...    0    0      0   
1455       1970          1970         0.0       252.0  ...    0    0      0   
1456       1960          1996         0.0      1224.0  ...    0    0      0   
1457       1992          1992         0.0       337.0  ...    0    0      0   
1458       1993          1994        94.0       758.0  ...    0    0      0   

      ConLI  ConLw  New  Oth  WD  P  Y  
0         0      0    0    0   1  0  1  
1         0      0    0    0   1  0  1  
2         0      0    0    0   1  0  1  
3         0      0    0    0   1  0  1  
4         0      0    0    0   1  0  1  
...     ...    ...  ...  ...  .. .. ..  
1454      0      0    0    0   1  0  1  
1455      0      0    0    0   1  0  1  
1456      0      0    0    0   1  0  1  
1457      0      0    0    0   1  0  1  
1458      0      0    0    0   1  0  1  

[1459 rows x 169 columns]

In [ ]:
test.isnull().sum()

Id               0
MSSubClass       0
LotFrontage    227
LotArea          0
OverallQual      0
              ... 
New              0
Oth              0
WD               0
P                0
Y                0
Length: 169, dtype: int64

# Removing Null values from Test set

In [ ]:
imputer=imputer.fit(test)
test_imp=imputer.transform(test)
test_x=pd.DataFrame(test_imp)
test_x

0      1      2        3    4    5       6       7      8       9    \
0     1461.0   20.0   80.0  11622.0  5.0  6.0  1961.0  1961.0    0.0   468.0   
1     1462.0   20.0   81.0  14267.0  6.0  6.0  1958.0  1958.0  108.0   923.0   
2     1463.0   60.0   74.0  13830.0  5.0  5.0  1997.0  1998.0    0.0   791.0   
3     1464.0   60.0   78.0   9978.0  6.0  6.0  1998.0  1998.0   20.0   602.0   
4     1465.0  120.0   43.0   5005.0  8.0  5.0  1992.0  1992.0    0.0   263.0   
...      ...    ...    ...      ...  ...  ...     ...     ...    ...     ...   
1454  2915.0  160.0   21.0   1936.0  4.0  7.0  1970.0  1970.0    0.0     0.0   
1455  2916.0  160.0   21.0   1894.0  4.0  5.0  1970.0  1970.0    0.0   252.0   
1456  2917.0   20.0  160.0  20000.0  5.0  7.0  1960.0  1996.0    0.0  1224.0   
1457  2918.0   85.0   62.0  10441.0  5.0  5.0  1992.0  1992.0    0.0   337.0   
1458  2919.0   60.0   74.0   9627.0  7.0  5.0  1993.0  1994.0   94.0   758.0   

      ...  159  160  161  162  163  164  165  166  167  168  
0     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
2     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
3     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
4     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
1454  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1455  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1456  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1457  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1458  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  

[1459 rows x 169 columns]

In [ ]:
test_x=pd.DataFrame(test_imp)
test_x

0      1      2        3    4    5       6       7      8       9    \
0     1461.0   20.0   80.0  11622.0  5.0  6.0  1961.0  1961.0    0.0   468.0   
1     1462.0   20.0   81.0  14267.0  6.0  6.0  1958.0  1958.0  108.0   923.0   
2     1463.0   60.0   74.0  13830.0  5.0  5.0  1997.0  1998.0    0.0   791.0   
3     1464.0   60.0   78.0   9978.0  6.0  6.0  1998.0  1998.0   20.0   602.0   
4     1465.0  120.0   43.0   5005.0  8.0  5.0  1992.0  1992.0    0.0   263.0   
...      ...    ...    ...      ...  ...  ...     ...     ...    ...     ...   
1454  2915.0  160.0   21.0   1936.0  4.0  7.0  1970.0  1970.0    0.0     0.0   
1455  2916.0  160.0   21.0   1894.0  4.0  5.0  1970.0  1970.0    0.0   252.0   
1456  2917.0   20.0  160.0  20000.0  5.0  7.0  1960.0  1996.0    0.0  1224.0   
1457  2918.0   85.0   62.0  10441.0  5.0  5.0  1992.0  1992.0    0.0   337.0   
1458  2919.0   60.0   74.0   9627.0  7.0  5.0  1993.0  1994.0   94.0   758.0   

      ...  159  160  161  162  163  164  165  166  167  168  
0     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
2     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
3     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
4     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
1454  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1455  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1456  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1457  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
1458  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  

[1459 rows x 169 columns]

 ### 1-LinearRegression

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics
model1 = LinearRegression()
model1.fit(train_x,y)
predict_x=model1.predict(test_x)
predict_x


array([ 99533.61222513, 135456.80981903, 174642.46815263, ...,
       147234.47511678, 109578.51013442, 223120.72233731])

In [ ]:
model1.score(train_x, y)

0.8908561821859884

### 2- KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn import metrics
model2 = KNeighborsClassifier()
model2.fit(train_x,y)
predict_x=model2.predict(test_x)
predict_x

array([131500, 151500, 155000, ..., 135000,  64500, 190000], dtype=int64)

In [ ]:
model2.score(train_x, y)

0.19726027397260273


### 3- Decision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
model3 = DecisionTreeClassifier( max_depth = 3)
model3.fit(train_x,y)
predict_x=model3.predict(test_x)
predict_x

array([115000, 155000, 190000, ..., 155000, 115000, 190000], dtype=int64)

In [ ]:

model3.score(train_x, y)

0.028082191780821917

### 4- Neural network

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

model4 = MLPClassifier(activation='tanh',  # can be also identity , logistic , relu
                                   solver='lbfgs',  # can be also sgd , adam
                                   learning_rate='constant',  # can be also invscaling , adaptive
                                   early_stopping=False,
                                   alpha=0.0001, hidden_layer_sizes=(100, 3), random_state = 33)

model4.fit(train_x,y)
predict_x=model4.predict(test_x)
predict_x



array([140000, 140000, 140000, ..., 140000, 140000, 140000], dtype=int64)

In [ ]:
model4.score(train_x, y)


0.0136986301369863

### 5- SVM

In [ ]:

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC


model5 = SVC()
model5.fit(train_x, y)

predict_x=model5.predict(test_x)
predict_x


array([140000, 190000, 140000, ..., 190000, 140000, 140000], dtype=int64)

In [ ]:
model5.score(train_x, y)

0.021232876712328767

### 6- Random forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

model6 = RandomForestClassifier(n_estimators = 20 , random_state = 30)
model6.fit(train_x,y)

predict_x=model6.predict(test_x)
predict_x

feature_list = list(x.columns)
feature_imp = pd.Series(model6.feature_importances_,index=feature_list).sort_values(ascending=False)
print(feature_imp)






Id             0.036078
GrLivArea      0.033683
TotalBsmtSF    0.032971
BsmtUnfSF      0.032193
LotArea        0.031995
                 ...   
Po             0.000103
Shed           0.000102
Sev            0.000102
RRNn           0.000083
Wood           0.000066
Length: 169, dtype: float64


In [ ]:
model6.score(train_x, y)

1.0

### 7-Naive

In [ ]:
from sklearn.naive_bayes import GaussianNB
model7 = GaussianNB()
model7.fit(train_x,y)
predict_x=model7.predict(test_x)
predict_x


array([129000, 190000, 173000, ..., 142500, 127500, 219500], dtype=int64)

In [ ]:

from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),train_x,y, cv=5)

c:\Users\SAMASOFT\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


array([0.02054795, 0.00684932, 0.01712329, 0.01712329, 0.01712329])

In [ ]:
model7.score(train_x, y)

0.7342465753424657

In [ ]:
import pickle

In [ ]:
filename = 'trained_model.sav'
pickle.dump(model6, open(filename, 'wb'))
#wb-----> write binary

In [ ]:
# loading the saved model
loaded_model = pickle.load(open('trained_model.sav', 'rb'))
#rb-----> read binary

In [ ]:
model6 = RandomForestClassifier(n_estimators = 20 , random_state = 30)
model6.fit(train_x,y)

predict_x=loaded_model.predict(test_x)
predict_x

feature_list = list(x.columns)
feature_imp = pd.Series(model6.feature_importances_,index=feature_list).sort_values(ascending=False)
print(feature_imp)



Id             0.036078
GrLivArea      0.033683
TotalBsmtSF    0.032971
BsmtUnfSF      0.032193
LotArea        0.031995
                 ...   
Po             0.000103
Shed           0.000102
Sev            0.000102
RRNn           0.000083
Wood           0.000066
Length: 169, dtype: float64
