# 1- Numpy(Create)  

### Import `Numpy` ?<a id='n.1'></a>


In [ ]:
import numpy as np

### `Create` an array of 10 zeros ?

In [ ]:
zero=np.repeat(0,10)
zero

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### `Create` an array of 10 Ones ?

In [ ]:
one=np.repeat(1,10)
one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### `Create` an array of 10 Fours ?

In [ ]:
four=np.repeat(4,10)
four

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

### `Create` an array of the Integers from 15 to 55 ?

In [ ]:
ints=np.arange(15,56,1,int)
ints

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

### `Create` an array of the Even Integers from 15 to 55 ?

In [ ]:
evints=np.arange(16,55,2,int)
evints

array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48,
       50, 52, 54])

### `Create` a Matrix (3×3) with Values  from 1 to 9 ?

In [ ]:
mat1=np.arange(1,10,1,int).reshape(3,3)
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### `Create` Identity Matrix (3×3) ?
[Types of Matrix](https://machinelearningmastery.com/introduction-to-types-of-matrices-in-linear-algebra/#:~:text=This%20tutorial%20is%20divided%20into%206%20parts%20to,Diagonal%20Matrix%205%20Identity%20Matrix%206%20Orthogonal%20Matrix)

In [ ]:
id=np.identity (3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### `Create` a random number between 0 and 1 `[0, 1)`?

In [ ]:
num1=np.random.random()
num1

0.9191058266039989

### `Create` an array of 10 `random` numbers between 0 and 1 `[0, 1)`?

In [ ]:
randarr=np.random.random(10)
randarr

array([0.27006914, 0.66606483, 0.75758504, 0.00371145, 0.94483273,
       0.40470256, 0.18151919, 0.66563261, 0.75905864, 0.67114702])

### `Create` a Matrix of 9 `random` numbers between 0 and 1 `[0, 1)`?

In [ ]:
randmat=np.random.random(9).reshape(3,3)
randmat

array([[0.86677011, 0.93435122, 0.29085858],
       [0.06081722, 0.8480526 , 0.10977056],
       [0.5355978 , 0.08402349, 0.81197437]])

### `Create` a Matrix of 9 `random` numbers?

In [ ]:
mat2=np.random.randn(9).reshape(3,3)
mat2

array([[-1.40229868,  0.25593688, -0.5599953 ],
       [-0.23707851, -1.06106355,  1.18130515],
       [ 0.51571059, -0.80953953,  1.04890465]])

### `Create` a Matrix of 9 `random` numbers integers  between `1 and 100`?

In [ ]:
mat3=np.random.randint(1,100,9).reshape(3,3)
mat3

array([[35, 74, 86],
       [81, 63, 27],
       [22, 66, 66]])

### `Create` a Array of 12 `random` numbers from a `standard normal distribution`?
[Standard Normal Distribution](https://www.educba.com/numpy-normal-distribution/)

In [ ]:
std=np.random.normal(0,1,12)
std

array([-0.17522547,  0.73850154,  1.69226053,  0.55757078, -2.04852125,
        0.69928229, -0.68855127,  0.67956272,  0.28181197,  0.59188973,
        0.36335703,  0.82285529])

### `Create` a Matrix of 100 numbers of `sorted`   between `0.01 and 1` ?

In [ ]:
sorted=np.arange(0.01,1.01,0.01).reshape(10,10)
sorted


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Good Job